# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180516_0044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
