# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180516_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
