# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180516_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_caption',
            field=models.TextField(null=True),
        ),
    ]
