# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20180516_0421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-pub_date']},
        ),
    ]
